language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
  - '10'
before_script:
  - chmod ugo+x __tests__/__fixtures__/test-push-server.git/hooks/update
  - chmod ugo+x __tests__/__fixtures__/test-push-server.git/hooks/post-receive
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
  - bash <(curl -s https://s3-ap-southeast-1.amazonaws.com/ci-scripts/ff-start-travis.sh)
branches:
  # Only build for PRs and the master branch (https://github.com/travis-ci/travis-ci/issues/1147#issuecomment-160820fvsvcsx262)
  only:
    - "master"
  except:
    - /^v\d+\.\d+\.\d+$/
addons:
  firefox: latest
  
